/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.io.File;

/**
 *
 * @author J
 */
public class FileUpload_Panel extends javax.swing.JPanel {

    /**
     * Creates new form FileUpload_Panel
     */
    public FileUpload_Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fileLocTF = new javax.swing.JTextField();
        keywordLocTF = new javax.swing.JTextField();
        GenerateB = new javax.swing.JButton();
        hintL = new javax.swing.JLabel();

        jLabel1.setText("云存储文件位置");

        jLabel2.setText("索引关键词位置");

        fileLocTF.setText("C:/Users/J/NetBeansProjects/files");
        fileLocTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileLocTFActionPerformed(evt);
            }
        });

        keywordLocTF.setText("C:/Users/J/NetBeansProjects/keywords.txt");

        GenerateB.setText("Generate");
        GenerateB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateBActionPerformed(evt);
            }
        });

        hintL.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        hintL.setForeground(new java.awt.Color(204, 51, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(GenerateB))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fileLocTF)
                    .addComponent(keywordLocTF, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                    .addComponent(hintL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(317, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileLocTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(keywordLocTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(GenerateB))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(hintL, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fileLocTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileLocTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileLocTFActionPerformed

    private void GenerateBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateBActionPerformed
        // TODO add your handling code here:
        File fileDir = new File(fileLocTF.getText());
        File keywordF = new File(keywordLocTF.getText());
        if (fileDir.exists() && fileDir.isDirectory() && keywordF.exists()){
            FileRunner fr = new FileRunner(Main_Frame.user, fileDir, keywordF);
            fr.process();
        }else{
            hintL.setText("Your input is not correct!");
        }        
    }//GEN-LAST:event_GenerateBActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GenerateB;
    private javax.swing.JTextField fileLocTF;
    private javax.swing.JLabel hintL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField keywordLocTF;
    // End of variables declaration//GEN-END:variables
}
